name: Tests

on: [push, pull_request]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and cache ffmpeg (all OS)
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
      id: setup-ffmpeg

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
          sudo apt-get -y install libpango1.0-dev

    - name: Install System Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cairo pango

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install
    
    - name: Run Tests
      run: |
        python -m poetry run pytest
